[OPTILINK]
# link is the slot where the optic link cable is connected in the pci express card
;link = 1
# is the node selected on the pci express card
;node = 0
# is the vme address set in the digitiser card
;vme_base_address = 32100000
# path where wavedump is installed. Normally it should be /usr/local/bin
;wavedump_path = /usr/local/bin

[USB]
use_usb = true

[RUN]
# number of events to measure
num_events = 100000
# time window in us, can change due to digitiser time resolution. The signal is about 6us after trigger
time = 5.12
# has to be an integer value between 0 and 100 inclusive
post_trigger_percent = 90
# time between each calibration due to temperature changes (in seconds)
time_calib = 120
# sample name
test_name = muon_test_1
# defines the CAEN input range. May change between models... 2.15 might be for these one
input_range = 2.15
# do simultaneous data conversion to root files. Recommended for low rates (very colimated sources)
simultaneous_conversion = true
# Show waveforms while taking data: recommended to check if everything is working as it should
plot_waveforms = true
# Generate triggers periodically to test without source
random_test = false

[SIGNAL]
channel_scintillator_0 = 0
channel_scintillator_1 = 1
channel_scintillator_2 = 2
channel_scintillator_3 = 3

thr_counts_0 = 100
thr_counts_1 = 100
thr_counts_2 = 100
thr_counts_3 = 100

[TRIGGER]
channel = 6
# base line offset guess in V
base_line = 0.2
# threshold in counts below base_line. If set too low, a set value of several sigmas will be used (look at code in channel class)
thr_counts = 1000

[ANTICOINCIDENCE]
channel = 7
# base line offset guess in V
base_line = 0.2
# threshold in counts below base_line. If set too low, a set value of several sigmas will be used (look at code in channel class)
thr_counts = 2

[OUTPUT]
dir = 2019_06
# waves
prefix = waves
suffix = t1
